language: csharp
solution: communications.sln
mono: none
dotnet: 2.1

# Specify which branches can be built on PR merge
branches:
  only:
    - master
    - development

script:
- dotnet restore

notifications:
    slack: sem5640-2018:Q6YaDYXwoxPIyBNjvo4qXGYa
